In [46]:
import numpy as np

In [51]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [56]:
np.mean(a, axis = 0, out = mean_a)
mean_a

array([2. , 8.4])

In [61]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [88]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
print(a_centered_sp)

8.0


In [89]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0

In [92]:
np.cov(a.T)[0, 1]

2.0