In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'svg'

In [2]:
# 1
a = np.arange(12,24,1)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [3]:
#2 
a1 = a.reshape(2, 6)
a2 = a.reshape(6, 2)
a3 = a.reshape(4, 3)
a4 = a.reshape(3, 4)
a5 = a.reshape(12, 1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [4]:
#3
a1 = a.reshape(2,-1)
a2 = a.reshape(-1, 2)
a3 = a.reshape(3, -1)
a4 = a.reshape(-1, 3)
a5 = a.reshape(12, -1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [5]:
# 4
# одномерный массив не является ни столбцом, ни вектором строки.
# Для того чтобы считать быть столбец с 12 строками массивом он 
#должен быть двухмерным массивом с одним измерением, установленным в единицу. 

In [6]:
# 5
t = np.random.normal(0, 1.0, size=(3,4))
t
print(t.size)
t1 = t.flatten()
print(t1.size)

12
12


In [7]:
#6
a = np.arange(20,0,-2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


In [8]:
#7
b = np.arange(20, 1, -2).reshape(1,10)
b
# Разница в массивах a и b в том, что a - одномерный, а b - двумерный с одним измерением, установленным в единицу

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [9]:
# 8 
a = np.zeros((2, 2))
b = np.zeros((3, 2))+1
print(a)
print(b)
v = np.vstack((a,b))
print(v)
print(v.size)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
10


In [22]:
# 9
a=np.arange(0, 12)
a = a.reshape((4, 3))
print(a)
At=a.T
print(At)
B = np.dot(a, At)
print(B)
print(B.shape)
np.linalg.det(B)
# определитель матрицы B = 0 соответветсвенно матрица B вырожденная 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
(4, 4)


0.0

In [30]:
# 10
np.random.seed(42)

In [34]:
# 11
c=np.random.randint(0, 16,16)
c
print(c.size)


16
[[11  9  5 12]
 [11  8  0 10]
 [10 14  9 15]
 [11 11 15 14]]


In [47]:
#12
C = c.reshape((4, 4))
print(C)
D=B+C*10
D
print(D)
D_det = np.linalg.det(D)
D_rank = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)
print(D_det)
print(D_rank)
print(D_inv)

[[11  9  5 12]
 [11  8  0 10]
 [10 14  9 15]
 [11 11 15 14]]
[[115 104  73 152]
 [124 130  86 222]
 [123 226 239 362]
 [142 232 362 442]]
62650800.0
4
[[ 0.01886552 -0.00325327 -0.01147599  0.00454519]
 [ 0.01683203 -0.02439777  0.02559361 -0.01449559]
 [ 0.01273886 -0.01565599 -0.00270994  0.00570208]
 [-0.02532897  0.02667356 -0.00752744  0.00374073]]


In [51]:
# 13
D_inv=np.where(D_inv<0, 0,1)
print(D_inv)
print(B)
print(C)
E=np.where(D_inv==1, B, C)
print(E)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[11  9  5 12]
 [11  8  0 10]
 [10 14  9 15]
 [11 11 15 14]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
